#!/usr/bin/env python3
"""
NL2SQL Clinic — FastAPI v5.1.0
Ibtcode Decision Engine — all layers active

BUGS FIXED vs 5.0.0:
  1. UPDATE confirmation — SQL generated by LLM BEFORE storing in pending,
     so /confirm has a real SQL to execute (not None → "nothing happens").
  2. Sensitive-column gate now returns needs_confirmation=True correctly —
     previously patient details leaked without confirmation.
  3. "heloo"/"how are you" → ibtcode CLARIFY returned instead of LLM call.
  4. DROP → hard 400 REJECT (no confirmation dialog, just blocked).
  5. Profanity → hard 400 REJECT immediately.
  6. All pending slots now store enough data for /confirm to work.

Start: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
"""

import os
import re
import sqlite3
import time
import json
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Optional, Tuple
from datetime import datetime

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field, field_validator

load_dotenv()

from cache         import query_cache
from logger_config import logger
from rate_limiter  import rate_limiter
from validators    import validate_question, validate_sql
from vanna_setup   import get_agent

from ibtcode.perception import detect_intent
from ibtcode.validation import (
    validate_perception,
    contains_profanity,
)
from ibtcode.context import Context
from ibtcode.audit   import AuditLogger

ibt_context = Context()
ibt_audit   = AuditLogger("nl2sql_audit.json")
_pending: Optional[Dict] = None

SENSITIVE_COLUMNS = {"phone", "email", "address", "date_of_birth", "dob"}


# ── DB helpers ─────────────────────────────────────────────────────────────────

def _db_path() -> str:
    return os.getenv("DB_PATH", "./clinic.db")


def _check_db() -> str:
    try:
        c = sqlite3.connect(_db_path()); c.execute("SELECT 1"); c.close()
        return "connected"
    except Exception:
        return "error"


def _execute_sql(sql: str) -> Tuple[Optional[List], Optional[List], int, int]:
    """Returns (cols, rows, row_count, affected_rows)."""
    try:
        conn = sqlite3.connect(_db_path())
        conn.row_factory = sqlite3.Row
        cur  = conn.cursor()
        cur.execute(sql)
        up = sql.strip().upper()
        if up.startswith("SELECT") or up.startswith("WITH"):
            rows = cur.fetchall()
            if rows:
                cols = [d[0] for d in cur.description]
                conn.close()
                return cols, [list(r) for r in rows], len(rows), 0
            conn.close()
            return None, None, 0, 0
        else:
            conn.commit()
            aff = cur.rowcount
            conn.close()
            return None, None, 0, aff
    except Exception as e:
        logger.error(f"[SQL] {e}")
        return None, None, 0, 0


def _delete_by_name(name: str) -> int:
    try:
        conn = sqlite3.connect(_db_path()); cur = conn.cursor()
        cur.execute(
            "DELETE FROM patients WHERE LOWER(first_name||' '||last_name)=LOWER(?)",
            (name,))
        conn.commit(); aff = cur.rowcount; conn.close()
        logger.info(f"[DELETE] exact '{name}' → {aff}")
        return aff
    except Exception as e:
        logger.error(f"[DELETE] exact: {e}"); return 0


def _delete_by_like(name: str) -> int:
    try:
        conn = sqlite3.connect(_db_path()); cur = conn.cursor()
        cur.execute(
            "DELETE FROM patients WHERE LOWER(first_name||' '||last_name) LIKE LOWER(?)",
            (f"%{name}%",))
        conn.commit(); aff = cur.rowcount; conn.close()
        logger.info(f"[DELETE] like '%{name}%' → {aff}")
        return aff
    except Exception as e:
        logger.error(f"[DELETE] like: {e}"); return 0


def _extract_patient_name(question: str) -> Optional[str]:
    patterns = [
        r"(?:delete|remove|erase)\s+patient\s+name\s+([A-Za-z\s]+)",
        r"(?:delete|remove|erase)\s+patient\s+([A-Za-z\s]+)",
        r"(?:delete|remove|erase)\s+([A-Za-z\s]+)\s+(?:from|patient)",
        r"(?:delete|remove|erase)\s+([A-Za-z\s]+)",
    ]
    noise = {"patient", "from", "the", "a", "an", "name"}
    for pat in patterns:
        m = re.search(pat, question, re.IGNORECASE)
        if m:
            parts = [w for w in m.group(1).strip().split()
                     if w.lower() not in noise]
            name = " ".join(parts).strip()
            if name:
                return name
    return None


def _classify(question: str) -> Dict:
    """ibtcode perception + keyword fallback."""
    try:
        p = detect_intent(question)
        intent, conf = p.get("intent", "UNKNOWN"), p.get("confidence", 0.5)
    except Exception:
        intent, conf = "UNKNOWN", 0.5

    if intent in ("UNKNOWN", None):
        q = question.lower()
        for mapped, kws in [
            ("PATIENT_QUERY",     ["patient","patients","registered","city","gender"]),
            ("DOCTOR_QUERY",      ["doctor","doctors","specialization","department"]),
            ("APPOINTMENT_QUERY", ["appointment","appointments","schedule","booking","visit","no-show"]),
            ("FINANCIAL_QUERY",   ["revenue","invoice","spending","cost","paid","total","amount","billing"]),
            ("SENSITIVE_QUERY",   ["phone","email","address","dob","birth","personal","contact"]),
            ("AGGREGATION_QUERY", ["count","average","sum","top","max","min","highest","percentage"]),
            ("TIME_QUERY",        ["month","year","date","quarter","trend","weekly","daily","last","past"]),
            ("TREATMENT_QUERY",   ["treatment","procedure","duration"]),
            ("COMPARISON_QUERY",  ["compare","versus","vs","department","breakdown"]),
        ]:
            if any(k in q for k in kws):
                return {"intent": mapped, "confidence": 0.85}
        return {"intent": "GENERAL_QUERY", "confidence": 0.6}

    return {"intent": intent, "confidence": conf}


def _col_risk(sql: str) -> Dict:
    lo = sql.lower()
    for col in SENSITIVE_COLUMNS:
        if re.search(rf"\b{col}\b", lo):
            return {"flag": True, "reason": f"Sensitive column accessed: {col}"}
    return {"flag": False}


def _audit(action, intent, state, risk, details=None):
    try:
        ibt_audit.log(action_name=action, intent=intent,
                      state=state, risk=risk, details=details or {})
        logger.info(f"[AUDIT] {action} | {intent} | {risk}")
    except Exception as e:
        logger.error(f"[AUDIT] {e}")


# ── LLM ────────────────────────────────────────────────────────────────────────

async def _run_llm(question: str) -> Dict:
    try:
        sql = get_agent().generate_sql(question)
        basic = validate_sql(sql)
        if not basic.valid:
            raise ValueError(basic.error)
        logger.info(f"[LLM] {sql[:200]}")
        cols, rows, cnt, aff = _execute_sql(sql)
        if cols and rows:
            return {"message": f"Found {cnt} result(s).", "sql_query": sql,
                    "columns": cols, "rows": rows, "row_count": cnt}
        if aff > 0:
            return {"message": f"{aff} row(s) affected.", "sql_query": sql,
                    "columns": None, "rows": None, "row_count": 0}
        return {"message": "No data found.", "sql_query": sql,
                "columns": None, "rows": None, "row_count": 0}
    except Exception as e:
        logger.error(f"[LLM] {e}")
        return await _fallback(question)


async def _fallback(question: str) -> Dict:
    logger.warning("[FALLBACK] rule-based")
    q = question.lower()
    rules = [
        (r"how many patients|total patients",
         "SELECT COUNT(*) AS total_patients FROM patients"),
        (r"top.{0,8}patients.{0,8}spend",
         "SELECT p.first_name||' '||p.last_name AS patient,SUM(i.total_amount) AS total "
         "FROM patients p JOIN invoices i ON p.id=i.patient_id "
         "GROUP BY p.id ORDER BY total DESC LIMIT 5"),
        (r"total revenue",
         "SELECT SUM(total_amount) AS revenue,SUM(paid_amount) AS collected,"
         "SUM(total_amount-paid_amount) AS outstanding FROM invoices"),
        (r"list.{0,6}doctors|show.{0,6}doctors",
         "SELECT name,specialization,department FROM doctors ORDER BY specialization"),
        (r"unpaid|overdue",
         "SELECT p.first_name||' '||p.last_name AS patient,"
         "i.total_amount,i.paid_amount,i.status FROM invoices i "
         "JOIN patients p ON p.id=i.patient_id "
         "WHERE i.status IN ('Pending','Overdue')"),
    ]
    for pat, sql in rules:
        if re.search(pat, q):
            cols, rows, cnt, _ = _execute_sql(sql)
            if rows:
                return {"message": f"Found {cnt} result(s). (fallback)",
                        "sql_query": sql, "columns": cols, "rows": rows, "row_count": cnt}
    return {"message": "Groq unavailable and no rule matched. Try again later.",
            "sql_query": None, "columns": None, "rows": None, "row_count": None}


# ── App ────────────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("NL2SQL Clinic v5.1 starting…")
    try:
        get_agent(); logger.info("Groq agent ready.")
    except Exception as e:
        logger.warning(f"Agent init: {e}")
    yield
    logger.info("Shutdown.")


app = FastAPI(title="NL2SQL Clinic", version="5.1.0", lifespan=lifespan)
app.add_middleware(CORSMiddleware, allow_origins=["*"],
                   allow_methods=["*"], allow_headers=["*"])


class ChatRequest(BaseModel):
    question: str = Field(..., min_length=3, max_length=500)
    @field_validator("question")
    @classmethod
    def strip_q(cls, v): return v.strip()


class ConfirmRequest(BaseModel):
    confirm: bool


class ChatResponse(BaseModel):
    question:           str
    message:            str
    sql_query:          Optional[str]            = None
    columns:            Optional[List[str]]       = None
    rows:               Optional[List[List[Any]]] = None
    row_count:          Optional[int]             = None
    cached:             bool                      = False
    latency_ms:         int                       = 0
    intent:             Optional[str]             = None
    risk:               Optional[str]             = None
    needs_confirmation: bool                      = False
    validation_status:  Optional[str]             = None


class HealthResponse(BaseModel):
    status: str; database: str; agent_memory_items: int
    cache_size: int; pending_confirm: bool; version: str = "5.1.0"


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse, tags=["UI"])
async def ui():
    p = os.path.join(os.path.dirname(__file__), "ui.html")
    return open(p).read() if os.path.exists(p) else \
        HTMLResponse("<h2>Place ui.html next to main.py</h2>", 404)


@app.get("/health", response_model=HealthResponse, tags=["System"])
async def health():
    try: mem = len(getattr(get_agent(), "agent_memory", []))
    except Exception: mem = 0
    return HealthResponse(status="ok", database=_check_db(),
                          agent_memory_items=mem, cache_size=query_cache.size(),
                          pending_confirm=_pending is not None)


@app.post("/chat", response_model=ChatResponse, tags=["Chat"])
async def chat(body: ChatRequest, request: Request):
    global _pending
    t0 = time.perf_counter()
    ip = request.client.host if request.client else "unknown"

    try:
        # Layer 1 — rate limit
        if not rate_limiter.is_allowed(ip):
            raise HTTPException(429, f"Rate limit: max {rate_limiter._max} req/min.")

        # Layer 2 — basic validation
        qv = validate_question(body.question)
        if not qv.valid:
            raise HTTPException(422, qv.error)

        logger.info(f"[CHAT] {ip}: {body.question!r}")

        # Layer 3 — profanity → hard reject
        if contains_profanity(body.question):
            _audit("REQUEST_REJECTED","BLOCKED","rejected","HIGH",
                   {"reason":"profanity","q":body.question[:80]})
            raise HTTPException(400,
                "Your query contains inappropriate language. Please rephrase.")

        # Layer 4 — ibtcode perception + validation
        p_result = _classify(body.question)
        intent, conf = p_result["intent"], p_result["confidence"]

        try:
            ctx_dict = ibt_context.to_dict()
        except AttributeError:
            ctx_dict = {
                "last_intent":    getattr(ibt_context, "last_intent", None),
                "last_timestamp": getattr(ibt_context, "last_timestamp", 0.0),
            }
        validation = validate_perception(
            {"intent": intent, "confidence": conf, "raw_input": body.question},
            context=ctx_dict,
        )
        v_status = validation.get("status", "VALID")
        logger.info(f"[VALIDATION] {v_status} intent={intent}")

        _audit("INTENT_DETECTED", intent, "processing", "LOW",
               {"question": body.question, "confidence": conf, "v_status": v_status})

        if v_status == "REJECT":
            _audit("REQUEST_REJECTED", intent, "rejected", "HIGH",
                   {"reason": validation.get("reason")})
            raise HTTPException(400, validation.get("message"))

        # CLARIFY — nonsense / off-topic / too-short
        if v_status == "CLARIFY":
            _audit("CLARIFICATION_NEEDED", intent, "clarify", "LOW",
                   {"reason": validation.get("reason")})
            return ChatResponse(
                question=body.question,
                message=validation.get("message",
                    "I couldn't understand that. Please ask a clinic-related question "
                    "(e.g. patients, doctors, appointments, revenue)."),
                intent=intent, risk="LOW", validation_status="CLARIFY",
                needs_confirmation=False, cached=False,
                latency_ms=int((time.perf_counter()-t0)*1000))

        q_lo    = body.question.lower()
        q_words = set(re.findall(r"\b\w+\b", q_lo))

        # Layer 5a — DROP → hard block
        if "drop" in q_words:
            _audit("DROP_BLOCKED","BLOCKED","rejected","CRITICAL",
                   {"question":body.question})
            raise HTTPException(400,
                "DROP is permanently blocked. This system is read-only "
                "except for confirmed DELETE/UPDATE.")

        # Layer 5b — DELETE / REMOVE / ERASE
        if q_words & {"delete", "remove", "erase"}:
            name = _extract_patient_name(body.question)
            if not name:
                return ChatResponse(
                    question=body.question,
                    message="Please specify the patient's full name. "
                            "Example: 'delete patient name Anjali Chopra'",
                    intent="DESTRUCTIVE_QUERY", risk="HIGH",
                    needs_confirmation=False, cached=False,
                    latency_ms=int((time.perf_counter()-t0)*1000))
            sql = (f"DELETE FROM patients "
                   f"WHERE LOWER(first_name||' '||last_name)=LOWER('{name}')")
            _pending = {"type":"DELETE","question":body.question,
                        "intent":"DESTRUCTIVE_QUERY","patient_name":name,
                        "sql":sql,"timestamp":time.time()}
            _audit("DELETE_CONFIRMATION_REQUIRED","DESTRUCTIVE_QUERY","pending","HIGH",
                   {"question":body.question,"patient_name":name})
            return ChatResponse(
                question=body.question,
                message=(f"⚠️ WARNING: You are about to DELETE patient '{name}'.\n"
                         f"This cannot be undone.\n"
                         f"POST /confirm {{\"confirm\": true}} to proceed, "
                         f"or {{\"confirm\": false}} to cancel."),
                sql_query=sql,
                intent="DESTRUCTIVE_QUERY", risk="HIGH",
                needs_confirmation=True, cached=False,
                latency_ms=int((time.perf_counter()-t0)*1000))

        # Layer 5c — UPDATE / MODIFY / CHANGE
        # FIX: generate SQL first, THEN decide whether to gate
        if q_words & {"update", "modify", "change"} or \
                re.search(r"\bupdate\b|\bmodify\b", q_lo):
            logger.info("[CHAT] UPDATE detected — generating SQL first")
            result = await _run_llm(body.question)
            gen_sql = result.get("sql_query", "")

            # If LLM returned SELECT (interpreted as a read query), just return it
            if gen_sql and gen_sql.strip().upper().startswith("SELECT"):
                logger.info("[CHAT] UPDATE keyword but LLM returned SELECT — safe")
                # fall through to normal return below with this result
            else:
                # Real UPDATE SQL — gate on confirmation
                _pending = {"type":"UPDATE","question":body.question,
                            "intent":"DESTRUCTIVE_QUERY","sql":gen_sql,
                            "result":result,"timestamp":time.time()}
                _audit("UPDATE_CONFIRMATION_REQUIRED","DESTRUCTIVE_QUERY","pending","HIGH",
                       {"question":body.question,"sql":gen_sql})
                return ChatResponse(
                    question=body.question,
                    message=(f"⚠️ WARNING: This will UPDATE data in the database.\n"
                             f"Review the SQL and confirm.\n"
                             f"POST /confirm {{\"confirm\": true}} to execute, "
                             f"or {{\"confirm\": false}} to cancel."),
                    sql_query=gen_sql,
                    intent="DESTRUCTIVE_QUERY", risk="HIGH",
                    needs_confirmation=True, cached=False,
                    latency_ms=int((time.perf_counter()-t0)*1000))

            # UPDATE keyword but SELECT sql — return normally (use result from above)
            latency = int((time.perf_counter()-t0)*1000)
            ibt_context.update(body.question, intent, "completed")
            _audit("QUERY_SUCCESS", intent, "completed", "LOW",
                   {"row_count": result.get("row_count"), "latency_ms": latency})
            return ChatResponse(
                question=body.question, cached=False, latency_ms=latency,
                intent=intent, risk="LOW", validation_status="VALID",
                needs_confirmation=False,
                **{k: result.get(k) for k in
                   ("message","sql_query","columns","rows","row_count")})

        # Layer 6 — cache
        cached = query_cache.get(body.question)
        if cached is not None:
            logger.info("[CHAT] cache hit")
            return ChatResponse(
                question=body.question, cached=True,
                latency_ms=int((time.perf_counter()-t0)*1000),
                intent=intent, risk="LOW", validation_status="VALID",
                needs_confirmation=False,
                **{k: cached[k] for k in
                   ("message","sql_query","columns","rows","row_count") if k in cached})

        # Layer 7 — LLM
        result = await _run_llm(body.question)

        # Layer 8 — sensitive column gate
        if result.get("sql_query"):
            cr = _col_risk(result["sql_query"])
            if cr["flag"]:
                _pending = {"type":"SENSITIVE","question":body.question,
                            "intent":intent,"sql":result["sql_query"],
                            "result":result,"timestamp":time.time()}
                _audit("SENSITIVE_DATA_CONFIRMATION_REQUIRED", intent, "pending",
                       "MEDIUM", {"question":body.question,"reason":cr["reason"]})
                return ChatResponse(
                    question=body.question,
                    message=(f"🔒 This query accesses sensitive patient data "
                             f"({cr['reason']}).\n"
                             f"POST /confirm {{\"confirm\": true}} to proceed."),
                    sql_query=result["sql_query"],
                    intent=intent, risk="MEDIUM",
                    needs_confirmation=True, cached=False,
                    latency_ms=int((time.perf_counter()-t0)*1000))

        latency = int((time.perf_counter()-t0)*1000)
        if result.get("sql_query") and result.get("rows") is not None:
            query_cache.set(body.question, result)

        ibt_context.update(body.question, intent, "completed")
        _audit("QUERY_SUCCESS", intent, "completed", "LOW",
               {"row_count": result.get("row_count"), "latency_ms": latency})

        return ChatResponse(
            question=body.question, cached=False, latency_ms=latency,
            intent=intent, risk="LOW", validation_status="VALID",
            needs_confirmation=False,
            **{k: result.get(k) for k in
               ("message","sql_query","columns","rows","row_count")})

    except HTTPException: raise
    except Exception as e:
        logger.error(f"[CHAT] {e}", exc_info=True)
        _audit("ERROR","UNKNOWN","error","HIGH",{"error":str(e),"q":body.question})
        raise HTTPException(500, f"Internal error: {str(e)[:200]}")


@app.post("/confirm", tags=["Chat"])
async def confirm(data: ConfirmRequest):
    global _pending
    if not _pending:
        return {"status": "no_pending", "message": "No pending action."}

    ptype  = _pending.get("type",   "unknown")
    intent = _pending.get("intent", "UNKNOWN")

    if not data.confirm:
        _audit("CONFIRMATION_CANCELLED", intent, "cancelled", "LOW",
               {"question": _pending.get("question"), "type": ptype})
        _pending = None
        return {"status": "cancelled", "message": "Operation cancelled."}

    # DELETE
    if ptype == "DELETE":
        name = _pending.get("patient_name", "")
        aff  = _delete_by_name(name)
        if aff == 0:
            aff = _delete_by_like(name)
        _audit("DELETE_EXECUTED","DESTRUCTIVE_QUERY","executed","HIGH",
               {"patient_name":name,"affected_rows":aff})
        _pending = None
        return {"status":"executed",
                "message":f"Deleted {aff} patient(s) matching '{name}'.",
                "affected_rows":aff}

    # UPDATE
    if ptype == "UPDATE":
        sql = _pending.get("sql")
        if not sql:
            _pending = None
            return {"status":"error","message":"No SQL was generated to execute."}
        _, _, _, aff = _execute_sql(sql)
        _audit("UPDATE_EXECUTED","DESTRUCTIVE_QUERY","executed","HIGH",
               {"sql":sql,"affected_rows":aff})
        _pending = None
        return {"status":"executed",
                "message":f"Update executed. {aff} row(s) affected.",
                "affected_rows":aff,"sql":sql}

    # SENSITIVE SELECT
    if ptype == "SENSITIVE":
        result = _pending.get("result", {})
        _audit("SENSITIVE_DATA_ACCESSED", intent, "executed","MEDIUM",
               {"question":_pending.get("question")})
        _pending = None
        return {"status":"executed","result":result}

    _pending = None
    return {"status":"error","message":f"Unknown pending type: {ptype}"}


@app.delete("/cache", tags=["System"])
async def clear_cache():
    query_cache.clear()
    return {"message":"Cache cleared.","status":"success"}


@app.get("/logs", tags=["System"])
async def get_logs(limit: int = 50):
    try:
        with open("nl2sql_audit.json") as f:
            logs = json.load(f)
        return {"logs": logs[-limit:], "total": len(logs)}
    except Exception:
        return {"logs": [], "total": 0}


@app.delete("/logs", tags=["System"])
async def clear_logs():
    try:
        with open("nl2sql_audit.json","w") as f: json.dump([],f)
        return {"message":"Logs cleared.","status":"success"}
    except Exception:
        return {"message":"Failed.","status":"error"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app",
                host=os.getenv("APP_HOST","0.0.0.0"),
                port=int(os.getenv("APP_PORT",8000)),
                reload=True,
                log_level=os.getenv("LOG_LEVEL","info").lower())